export const products = [
  {
    id: 1,
    name: 'apple',
    manufacturer: 'FreshO',
    unitPrice: 120,
    imageUrl: 'img/fruits/apple.png',
    quantityInBasket: 0,
    quantityAvailable: 20,
    category: 'Fruits & Vegatables',
  },
  {
    id: 2,
    name: 'table cloth',
    manufacturer: 'FreshO',
    unitPrice: 200,
    imageUrl: 'img/household/tablecloth.png',
    quantityInBasket: 0,
    quantityAvailable: 3,
    category: 'Household Items',
  },
  {
    id: 3,
    name: 'butter',
    manufacturer: 'FreshO',
    unitPrice: 20,
    imageUrl: 'img/dairy/butter.png',
    quantityInBasket: 0,
    quantityAvailable: 2,
    category: 'Dairy & Eggs',
  },
];
